## 作业1

### 逐个更新权重，多次迭代

In [1]:
from mxnet import nd

In [2]:
def stepFunction(x):
    return 1 if x.asscalar() >0 else 0
def getDataset():
    xs=nd.array([[1,1],[1,0],[0,1],[0,0]])
    ys=nd.array([1,0,0,0])
    return xs,ys

In [3]:
class Perceptron(object):
    def __init__(self,activator):#初始化变量
        self.activator=activator
        self.weights=nd.array([])
        self.bias=nd.zeros(1)
    def __str__(self):#特殊函数，输出字符串
        w=self.weights.asnumpy().tolist()
        b=self.bias.asnumpy().tolist()
        strw='weights:%s'%w
        strb='bias:%s'%b
        return strw+'\n'+strb
    def net(self,x):#计算输出值，预测值
        result=self.activator(nd.dot(self.weights,x)+self.bias)
        return result
    def updateWeights(self,x,yhat,y,eta):#更新权重和偏差
        deltaw=eta*(y-yhat)*x
        self.weights+=deltaw

        deltab=eta*(y-yhat)
        self.bias+=deltab
    def epoch(self,xs,ys,eta):#逐个计算预测值，然后更新权重
        for x ,y in zip(xs,ys):
            yhat=self.net(x)
            self.updateWeights(x,yhat,y,eta)
    def train(self,xs,ys,epochs,eta):#初始化权重，迭代更新权重
        inputNum=len(xs[0])
        self.weights=nd.zeros(inputNum)
        for i in range(epochs):
            self.epoch(xs,ys,eta)

In [4]:
xs,ys=getDataset()
xs,ys

(
 [[ 1.  1.]
  [ 1.  0.]
  [ 0.  1.]
  [ 0.  0.]]
 <NDArray 4x2 @cpu(0)>, 
 [ 1.  0.  0.  0.]
 <NDArray 4 @cpu(0)>)

In [5]:
andP=Perceptron(stepFunction)

In [6]:
print(andP)

weights:[]
bias:[0.0]


In [7]:
andP.train(xs,ys,10,0.01)

In [8]:
print(andP)

weights:[0.009999999776482582, 0.019999999552965164]
bias:[-0.019999999552965164]


In [9]:
for x in xs:
    print(x.asnumpy().tolist(),andP.net(x))

[1.0, 1.0] 1
[1.0, 0.0] 0
[0.0, 1.0] 0
[0.0, 0.0] 0


In [10]:
x=nd.array([1,2])

In [11]:
x.shape

(2,)

## 作业2

In [12]:
xs,ys=getDataset()
xs,ys

(
 [[ 1.  1.]
  [ 1.  0.]
  [ 0.  1.]
  [ 0.  0.]]
 <NDArray 4x2 @cpu(0)>, 
 [ 1.  0.  0.  0.]
 <NDArray 4 @cpu(0)>)

In [13]:
w=andP.weights
w


[ 0.01  0.02]
<NDArray 2 @cpu(0)>

In [14]:
nd.dot(xs,w.T)


[ 0.03  0.01  0.02  0.  ]
<NDArray 4 @cpu(0)>

## 作业3
- 数据输入集不变，输出集变为[1,1,1,0]

In [15]:
def ORgetDataset():
    xs=nd.array([[1,1],[1,0],[0,1],[0,0]])
    ys=nd.array([1,1,1,0])
    return xs,ys

In [16]:
xs,ys=ORgetDataset()
xs,ys 

(
 [[ 1.  1.]
  [ 1.  0.]
  [ 0.  1.]
  [ 0.  0.]]
 <NDArray 4x2 @cpu(0)>, 
 [ 1.  1.  1.  0.]
 <NDArray 4 @cpu(0)>)

In [17]:
orP=Perceptron(stepFunction)

In [18]:
print(orP)

weights:[]
bias:[0.0]


In [19]:
orP.train(xs,ys,10,0.01)

In [20]:
print(orP)

weights:[0.009999999776482582, 0.009999999776482582]
bias:[0.0]


In [21]:
for i in xs:
    print(i.asnumpy().tolist(),orP.net(i))

[1.0, 1.0] 1
[1.0, 0.0] 1
[0.0, 1.0] 1
[0.0, 0.0] 0
